name: Generated APK AAB

env:
  main_project_module: app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: forgejo.event_name == 'workflow_dispatch' || (forgejo.event_name == 'push' && (startsWith(forgejo.event.head_commit.message, '[build]') || startsWith(forgejo.event.head_commit.message, '[release]')))
    runs-on: node
    steps:
      - uses: actions/checkout@v4

      - name: Install ZIP Util
        run: |
          apt-get update
          apt-get install zip -y

      - name: Get App Version
        id: app_version
        run: |
          VERSION_NAME=$(sed -n 's/.*versionName = "\(.*\)".*/\1/p' ${{ env.main_project_module }}/build.gradle.kts | head -1)
          echo "app_version=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "Found version: $VERSION_NAME"

      - name: Get NDK Version
        id: ndk_version
        run: |
          NDK_VERSION=$(sed -n 's/.*ndkVersion = "\(.*\)".*/\1/p' ${{ env.main_project_module }}/build.gradle.kts | head -1)
          echo "ndk_version=$NDK_VERSION" >> $GITHUB_OUTPUT
          echo "Found NDK version: $NDK_VERSION"

      - name: Get Commit SHA
        id: sha
        run: |
          echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
#          cache: 'gradle'

      - name: Setup Android SDK
        uses: https://github.com/android-actions/setup-android@v3
        with:
          packages: 'tools build-tools;36.0.0 platform-tools ndk;${{ steps.ndk_version.outputs.ndk_version }}'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build All Artifacts
        run: |
          # ./gradlew assembleFdroidRelease
          # ./gradlew assembleApkRelease
          # ./gradlew ${{ env.main_project_module }}:bundlePlayRelease
          ./gradlew assembleRelease
          ./gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Zip Native Debug Symbols
        run: |
          mkdir -p ${{ github.workspace }}/output
          
          # SYMBOLS_DIR="${{ env.main_project_module }}/build/intermediates/merged_native_libs/playRelease/mergePlayReleaseNativeLibs/out/lib/"
          SYMBOLS_DIR="${{ env.main_project_module }}/build/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib/"
          
          if [ -d "$SYMBOLS_DIR" ]; then
            cd "$SYMBOLS_DIR"
          
            zip -r ${{ github.workspace }}/output/native-debug-symbols.zip .
            cd -
          
            echo "Symbols zipped successfully"
          else
            echo "Warning: Native symbols directory not found. Skipping zip"
          fi

      - name: Prepare for signing
        run: |
          mkdir -p signing_staging

          # cp ${{ env.main_project_module }}/build/outputs/apk/apk/release/*.apk signing_staging/
          # cp ${{ env.main_project_module }}/build/outputs/apk/fdroid/release/*.apk signing_staging/
          # cp ${{ env.main_project_module }}/build/outputs/bundle/playRelease/*.aab signing_staging/
          cp ${{ env.main_project_module }}/build/outputs/apk/release/*.apk signing_staging/
          cp ${{ env.main_project_module }}/build/outputs/bundle/release/*.aab signing_staging/

      - name: Sign Release Artifacts
        run: |
          set -e

          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > keystore.jks

          for apk in signing_staging/*.apk; do
            ${ANDROID_SDK_ROOT}/build-tools/36.0.0/apksigner sign \
              --ks keystore.jks \
              --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
              --ks-pass "pass:${{ secrets.KEYSTORE_PASSWORD }}" \
              --key-pass "pass:${{ secrets.KEY_PASSWORD }}" \
              --v1-signing-enabled false \
              --v2-signing-enabled true \
              --v3-signing-enabled true \
              --out "${apk%.apk}-signed.apk" \
              "$apk"
          done

          for aab in signing_staging/*.aab; do
            jarsigner \
              -keystore keystore.jks \
              -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
              -keypass "${{ secrets.KEY_PASSWORD }}" \
              -signedjar "${aab%.aab}-signed.aab" \
              "$aab" "${{ secrets.KEY_ALIAS }}"
          done

          rm keystore.jks

      - name: Copy signed artifacts to output
        run: |
          # ---- reminder for myself, if this apk file name is changed, change in the froid repo too in the binary part ----
          # cp signing_staging/*fdroid*-signed*.apk ${{ github.workspace }}/output/app-fdroid-release-signed.apk
          # cp signing_staging/*apk*-signed*.apk ${{ github.workspace }}/output/app-apk-release-signed.apk
          cp signing_staging/*-signed*.apk ${{ github.workspace }}/output/
          cp signing_staging/*-signed*.aab ${{ github.workspace }}/output/

      - name: Publish Release
        uses: actions/forgejo-release@v2.7.3
        env:
          GITHUB_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        with:
          direction: upload
          prerelease: false
          url: https://git.stefdp.com
          repo: Stef/Pterodactyl-Panel-Android-App
          token: ${{ secrets.FORGEJO_TOKEN }}
          tag: "v${{ steps.app_version.outputs.app_version }}"
          release-dir: ${{ github.workspace }}/output