package com.stefdp.pterodactylpanel.network

import com.stefdp.pterodactylpanel.network.models.RecoveryCodes
import com.stefdp.pterodactylpanel.network.models.ServerDatabase
import com.stefdp.pterodactylpanel.network.models.ServerFile
import com.stefdp.pterodactylpanel.network.models.ServerSchedule
import com.stefdp.pterodactylpanel.network.models.ServerStats
import com.stefdp.pterodactylpanel.network.models.SignedUrl
import com.stefdp.pterodactylpanel.network.models.SshKey
import com.stefdp.pterodactylpanel.network.models.User
import com.stefdp.pterodactylpanel.network.models.requests.AddClientSshKeyBody
import com.stefdp.pterodactylpanel.network.models.requests.ClientSendCommandToServerBody
import com.stefdp.pterodactylpanel.network.models.requests.ClientSendPowerSignalToServerBody
import com.stefdp.pterodactylpanel.network.models.requests.CompressClientServerFilesBody
import com.stefdp.pterodactylpanel.network.models.requests.CopyClientServerFileBody
import com.stefdp.pterodactylpanel.network.models.requests.CreateClientApiKeyBody
import com.stefdp.pterodactylpanel.network.models.requests.CreateClientServerDatabaseBody
import com.stefdp.pterodactylpanel.network.models.requests.CreateClientServerFolderBody
import com.stefdp.pterodactylpanel.network.models.requests.CreateClientServerScheduleBody
import com.stefdp.pterodactylpanel.network.models.requests.CreateClientServerScheduleTaskBody
import com.stefdp.pterodactylpanel.network.models.requests.DecompressClientServerFileBody
import com.stefdp.pterodactylpanel.network.models.requests.DeleteClientServerFilesBody
import com.stefdp.pterodactylpanel.network.models.requests.DisableClient2FABody
import com.stefdp.pterodactylpanel.network.models.requests.EnableClient2FABody
import com.stefdp.pterodactylpanel.network.models.requests.GetClientActivityQueryInclude
import com.stefdp.pterodactylpanel.network.models.requests.GetClientActivityQuerySort
import com.stefdp.pterodactylpanel.network.models.requests.GetClientServersQueryType
import com.stefdp.pterodactylpanel.network.models.requests.RemoveClientSshKeyBody
import com.stefdp.pterodactylpanel.network.models.requests.RenameClientServerFilesBody
import com.stefdp.pterodactylpanel.network.models.requests.UpdateClientEmailBody
import com.stefdp.pterodactylpanel.network.models.requests.UpdateClientPasswordBody
import com.stefdp.pterodactylpanel.network.models.requests.UpdateClientServerFilePermissionsBody
import com.stefdp.pterodactylpanel.network.models.requests.UpdateClientServerScheduleTaskBody
import com.stefdp.pterodactylpanel.network.models.responses.GetClient2FAQrCodeResponse
import com.stefdp.pterodactylpanel.network.models.responses.GetClientAvailablePermissionsResponse
import com.stefdp.pterodactylpanel.network.models.responses.GetClientServerResponse
import com.stefdp.pterodactylpanel.network.models.responses.GetClientServerSchedulesResponse
import com.stefdp.pterodactylpanel.network.models.responses.GetClientServersResponse
import com.stefdp.pterodactylpanel.network.models.responses.GetClientSshKeysResponse
import com.stefdp.pterodactylpanel.network.models.responses.ListClientApiKeysResponse
import com.stefdp.pterodactylpanel.network.models.responses.ListClientServerDatabasesResponse
import com.stefdp.pterodactylpanel.network.models.responses.ListClientServerFilesResponse
import okhttp3.MultipartBody
import okhttp3.ResponseBody
import retrofit2.Response
import retrofit2.http.Body
import retrofit2.http.DELETE
import retrofit2.http.GET
import retrofit2.http.Header
import retrofit2.http.POST
import retrofit2.http.PUT
import retrofit2.http.Part
import retrofit2.http.Path
import retrofit2.http.Query
import retrofit2.http.Streaming
import retrofit2.http.Url

// TODO: reminder for myself, api auth is "Bearer <API_KEY>"
/* docs:
- https://registry.scalar.com/@default-team-68o6n/apis/pterodactyl-panel-api@1.0.0#tag/client-server-network
    - docs OpenAPI file generated by opencode and displayed via scalar.com
- https://old-api.redbanana.dev/docs/client-server-schedules/post-update-task
    - old docs backed up by a pterodactyl panel Discord server moderator
- https://pterodactyl-api-docs.netvpx.com/docs/api/client/schedules#update-schedule-task
    - official docs but according to a moderator fo the discord, generated with AI and includes hallucinations

i legit don't know which one to follow now 😭
*/

interface PterodactylApiService {
    @GET("client")
    fun getClientServers(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Query("per_page") perPage: Int? = null,
        @Query("page") page: Int? = null,
        @Query("filter[name]") filterName: String? = null,
        @Query("filter[uuid]") filterUuid: String? = null,
        @Query("filter[external_id]") filterExternalId: String? = null,
        @Query("filter[description]") filterDescription: String? = null,
        @Query("filter[*]") filterAny: String? = null,
        @Query("type") type: GetClientServersQueryType
    ): Response<GetClientServersResponse>

    @GET("client/permissions")
    fun getClientAvailablePermissions(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
    ): Response<GetClientAvailablePermissionsResponse>

    @GET("client/account")
    fun getClient(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json"
    ): Response<User>

    @GET("client/account/two-factor")
    fun getClient2FAQrCode(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json"
    ): Response<GetClient2FAQrCodeResponse>

    @POST("client/account/two-factor")
    fun enableClient2FA(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Body data: EnableClient2FABody
    ): Response<RecoveryCodes>

    @POST("client/account/two-factor")
    fun disableClient2FA(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Body data: DisableClient2FABody
    )

    @PUT("client/account/email")
    fun updateClientEmail(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Body data: UpdateClientEmailBody
    )

    @PUT("client/account/password")
    fun updateClientPassword(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Body data: UpdateClientPasswordBody
    )

    @GET("client/account/api-keys")
    fun listClientApiKeys(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
    ): Response<ListClientApiKeysResponse>

    @POST("client/account/api-keys")
    fun createClientApiKey(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Body data: CreateClientApiKeyBody
    )

    @DELETE("client/account/api-keys/{identifier}")
    fun deleteClientApiKey(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") keyId: String,
    )

    @GET("client/account/activity")
    fun getClientActivity(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Query("filter[event]") filterEvent: String? = null,
        @Query("sort") sort: GetClientActivityQuerySort? = null,
        @Query("include") include: GetClientActivityQueryInclude? = null,
        @Query("per_page") perPage: Int? = null,
        @Query("page") page: Int? = null,
    )

    @GET("client/account/ssh-keys")
    fun getClientSshKeys(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
    ): Response<GetClientSshKeysResponse>

    @POST("client/account/ssh-keys")
    fun addClientSshKey(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Body data: AddClientSshKeyBody
    ): Response<SshKey>

    @POST("client/account/ssh-keys/remove")
    fun removeClientSshKey(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Body data: RemoveClientSshKeyBody
    )

    @GET("client/servers/{identifier}")
    fun getClientServer(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
    ): Response<GetClientServerResponse>

    @GET("client/servers/{identifier}/resources")
    fun getClientServerResources(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
    ): Response<ServerStats>

    @POST("client/servers/{identifier}/command")
    fun clientSendCommandToServer(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Body data: ClientSendCommandToServerBody
    )

    @POST("client/servers/{identifier}/power")
    fun clientSendPowerSignalToServer(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Body data: ClientSendPowerSignalToServerBody
    )

    @GET("client/servers/{identifier}/databases")
    fun listClientServerDatabases(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
    ): Response<ListClientServerDatabasesResponse>

    @POST("client/servers/{identifier}/databases")
    fun createClientServerDatabase(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Body data: CreateClientServerDatabaseBody
    ): Response<ServerDatabase>

    @POST("client/server/{serverIdentifier}/databases/{databaseIdentifier)/rotate-password")
    fun rotateClientServerDatabasePassword(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("serverIdentifier") serverId: String,
        @Path("databaseIdentifier") databaseId: String,
    ): Response<ServerDatabase>

    @DELETE("client/server/{serverIdentifier}/databases/{databaseIdentifier}")
    fun deleteClientServerDatabase(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("serverIdentifier") serverId: String,
        @Path("databaseIdentifier") databaseId: String,
    ): Response<ServerDatabase>

    @GET("client/servers/{identifier}/files/list")
    fun listClientServerFiles(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Query("directory") directory: String? = null,
    ): Response<ListClientServerFilesResponse>

    @GET("client/servers/{identifier}/files/contents")
    fun getClientServerFileContents(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Query("file") file: String, // for "/home/container/file.txt" it'd be "/file.txt"
    ): Response<String>

    @GET("client/servers/{identifier}/files/download")
    fun getDownloadClientServerFileUrl(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Query("file") file: String
    ): Response<SignedUrl>

    @Streaming
    @GET
    fun downloadClientServerFile(
//        @Header("Authorization") authorization: String, // not sure if this requires auth or not
        @Url fileUrl: String, // the url returned by getDownloadClientServerFileUrl's response
    ): Response<ResponseBody>

    @POST("client/servers/{identifier}/files/write")
    fun writeClientServerFile(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Query("file") file: String,
        @Body fileContents: String,
    )

    @POST("client/servers/{identifier}/files/create-folder")
    fun createClientServerFolder(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Body data: CreateClientServerFolderBody
    )

    @POST("client/servers/{identifier}/files/copy")
    fun copyClientServerFile(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Body data: CopyClientServerFileBody
    )

    @PUT("client/servers/{identifier}/files/rename")
    fun renameClientServerFiles(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Body data: RenameClientServerFilesBody
    )

    @POST("client/servers/{identifier}/files/compress")
    fun compressClientServerFiles(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Body data: CompressClientServerFilesBody
    ): Response<ServerFile>

    @POST("client/servers/{identifier}/files/decompress")
    fun decompressClientServerFile(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Body data: DecompressClientServerFileBody
    )

    @POST("client/servers/{identifier}/files/delete")
    fun deleteClientServerFiles(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Body data: DeleteClientServerFilesBody
    )

    @GET("client/servers/{identifier}/files/upload")
    fun geUploadClientServerFileUrl(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Query("directory") directory: String? = null,
    ): Response<SignedUrl>

    // TODO: if i can't get this to work, i'll just use use writeClientServerFile instead
    @POST
    fun uploadClientServerFile(
//        @Header("Authorization") authorization: String, // not sure if this requires auth or not
        @Url uploadUrl: String,
        @Part files: List<MultipartBody.Part>, // haven't tested that, idk if it actually works
        @Part("directory") directory: String, // idk if that'll work either
    )

    @POST("client/servers/{identifier}/files/chmod")
    fun updateClientServerFilePermissions(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Body data: UpdateClientServerFilePermissionsBody
    )

    @GET("client/servers/{identifier}/schedules")
    fun getClientServerSchedules(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
    ): Response<GetClientServerSchedulesResponse>

    @GET("client/servers/{serverIdentifier}/schedules/{scheduleIdentifier}")
    fun getClientServerSchedule(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("serverIdentifier") serverId: String,
        @Path("scheduleIdentifier") scheduleId: String,
    ): Response<ServerSchedule>

    @POST("client/servers/{identifier}/schedules")
    fun createClientServerSchedule(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("identifier") serverId: String,
        @Body data: CreateClientServerScheduleBody
    ): Response<ServerSchedule>

    @POST("client/servers/{serverIdentifier}/schedules/{scheduleIdentifier}")
    fun updateClientServerSchedule(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("serverIdentifier") serverId: String,
        @Path("scheduleIdentifier") scheduleId: String,
    ): Response<ServerSchedule>

    @DELETE("client/servers/{serverIdentifier}/schedules/{scheduleIdentifier}")
    fun deleteClientServerSchedule(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("serverIdentifier") serverId: String,
        @Path("scheduleIdentifier") scheduleId: String,
    )

    @POST("client/servers/{serverIdentifier}/schedules/{scheduleIdentifier}/tasks")
    fun createClientServerScheduleTask(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("serverIdentifier") serverId: String,
        @Path("scheduleIdentifier") scheduleId: String,
    ): Response<CreateClientServerScheduleTaskBody>

    @POST("client/servers/{serverIdentifier}/schedules/{scheduleIdentifier}/tasks/{taskIdentifier}")
    fun updateClientServerScheduleTask(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("serverIdentifier") serverId: String,
        @Path("scheduleIdentifier") scheduleId: String,
        @Path("taskIdentifier") taskId: String,
    ): Response<UpdateClientServerScheduleTaskBody>

    @DELETE("client/servers/{serverIdentifier}/schedules/{scheduleIdentifier}/tasks/{taskIdentifier}")
    fun deleteClientServerScheduleTask(
        @Header("Authorization") authorization: String,
        @Header("Accept") accept: String = "Application/vnd.pterodactyl.v1+json",
        @Header("Content-Type") contentType: String = "application/json",
        @Path("serverIdentifier") serverId: String,
        @Path("scheduleIdentifier") scheduleId: String,
        @Path("taskIdentifier") taskId: String,
    )
}