package com.stefdp.pterodactylpanel.ui.theme

import androidx.compose.ui.graphics.Color
import com.neoutils.highlight.core.util.UiColor

const val stringLiteral = "#CE9178"
const val customLiteral = "#DCDCAA"
const val numberLiteral = "#B5CEA8"
const val newOperator = "#C586C0"
const val tags = "#569cd6"
const val htmlTagBrackets = "#808080"
const val header = "#4FC1FF"
const val comment = "#6A9955"
const val constantsAndOptions = tags
const val labels = "#C8C8C8"
const val attributes = "#9CDCFE"
const val escapeCharacters = "#D7BA7D"
const val functionDeclarations = customLiteral
const val typesDeclarationAndReferences = "#4EC9B0"
const val typesDeclarationAndReferencesTSGrammar = typesDeclarationAndReferences
const val controlFlowAndSpecialKeywords = newOperator
const val variableAndParameterName = attributes
const val constantsAndEnums = "#4FC1FF"
const val objectKeysTSGrammar = attributes
const val cssPropertyValue = stringLiteral
const val cssTags = escapeCharacters
const val cssClassesAndIDs = cssTags
const val markdownBold = tags
const val markdownHeading = markdownBold
const val markdownItalic = newOperator
const val markdownQuotePunctuation = comment
const val markdownListPunctuation = "#6796e6"
const val inlineCodeAndRawMarkup = stringLiteral
const val diffInserted = numberLiteral
const val diffDeleted = stringLiteral
const val diffChanged = tags
const val diffHeader = tags
const val preprocessorDirectives = tags
const val preprocessorStrings = stringLiteral
const val preprocessorNumbers = numberLiteral
const val pythonDictionaryKeys = attributes
const val javaImportsAndPackageIdentifier = "#D4D4D4"

val colorStringLiteral = UiColor.Hex(stringLiteral)
val colorCustomLiteral = UiColor.Hex(customLiteral)
val colorNumberLiteral = UiColor.Hex(numberLiteral)
val colorNewOperator = UiColor.Hex(newOperator)
val colorTags = UiColor.Hex(tags)
val colorHtmlTagBrackets = UiColor.Hex(htmlTagBrackets)
val colorHeader = UiColor.Hex(header)
val colorComment = UiColor.Hex(comment)
val colorConstantsAndOptions = UiColor.Hex(constantsAndOptions)
val colorLabels = UiColor.Hex(labels)
val colorAttributes = UiColor.Hex(attributes)
val colorEscapeCharacters = UiColor.Hex(escapeCharacters)
val colorFunctionDeclarations = UiColor.Hex(functionDeclarations)
val colorTypesDeclarationAndReferences = UiColor.Hex(typesDeclarationAndReferences)
val colorTypesDeclarationAndReferencesTSGrammar = UiColor.Hex(typesDeclarationAndReferencesTSGrammar)
val colorControlFlowAndSpecialKeywords = UiColor.Hex(controlFlowAndSpecialKeywords)
val colorVariableAndParameterName = UiColor.Hex(variableAndParameterName)
val colorConstantsAndEnums = UiColor.Hex(constantsAndEnums)
val colorObjectKeysTSGrammar = UiColor.Hex(objectKeysTSGrammar)
val colorCssPropertyValue = UiColor.Hex(cssPropertyValue)
val colorCssTags = UiColor.Hex(cssTags)
val colorCssClassesAndIDs = UiColor.Hex(cssClassesAndIDs)
val colorMarkdownBold = UiColor.Hex(markdownBold)
val colorMarkdownHeading = UiColor.Hex(markdownHeading)
val colorMarkdownItalic = UiColor.Hex(markdownItalic)
val colorMarkdownQuotePunctuation = UiColor.Hex(markdownQuotePunctuation)
val colorMarkdownListPunctuation = UiColor.Hex(markdownListPunctuation)
val colorInlineCodeAndRawMarkup = UiColor.Hex(inlineCodeAndRawMarkup)
val colorDiffInserted = UiColor.Hex(diffInserted)
val colorDiffDeleted = UiColor.Hex(diffDeleted)
val colorDiffChanged = UiColor.Hex(diffChanged)
val colorDiffHeader = UiColor.Hex(diffHeader)
val colorPreprocessorDirectives = UiColor.Hex(preprocessorDirectives)
val colorPreprocessorStrings = UiColor.Hex(preprocessorStrings)
val colorPreprocessorNumbers = UiColor.Hex(preprocessorNumbers)
val colorPythonDictionaryKeys = UiColor.Hex(pythonDictionaryKeys)
val colorJavaImportsAndPackageIdentifier = UiColor.Hex(javaImportsAndPackageIdentifier)